// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyASp86IAiUbkh3F8QKEj-xSLGaYUAHGz7Y',
    appId: '1:877090275985:web:c513b0763e937e4016b530',
    messagingSenderId: '877090275985',
    projectId: 'travelguide-4b1fc',
    authDomain: 'travelguide-4b1fc.firebaseapp.com',
    storageBucket: 'travelguide-4b1fc.appspot.com',
    measurementId: 'G-TYS1HZVK8Y',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDDtjnaLWEACwVmf_nwQSZP9BscddAu6uI',
    appId: '1:877090275985:android:2e385564c5d18f2416b530',
    messagingSenderId: '877090275985',
    projectId: 'travelguide-4b1fc',
    storageBucket: 'travelguide-4b1fc.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAHb4rrSUD-pgV4QiHJ8DdVqRkousT_9Qs',
    appId: '1:877090275985:ios:807b74f392091a2d16b530',
    messagingSenderId: '877090275985',
    projectId: 'travelguide-4b1fc',
    storageBucket: 'travelguide-4b1fc.appspot.com',
    iosBundleId: 'com.example.travelguide',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAHb4rrSUD-pgV4QiHJ8DdVqRkousT_9Qs',
    appId: '1:877090275985:ios:807b74f392091a2d16b530',
    messagingSenderId: '877090275985',
    projectId: 'travelguide-4b1fc',
    storageBucket: 'travelguide-4b1fc.appspot.com',
    iosBundleId: 'com.example.travelguide',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyASp86IAiUbkh3F8QKEj-xSLGaYUAHGz7Y',
    appId: '1:877090275985:web:e859701b3e4367cc16b530',
    messagingSenderId: '877090275985',
    projectId: 'travelguide-4b1fc',
    authDomain: 'travelguide-4b1fc.firebaseapp.com',
    storageBucket: 'travelguide-4b1fc.appspot.com',
    measurementId: 'G-4DHSJTPZLE',
  );
}
